default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ma_development

test:
  <<: *default
  database: ma_test

production:
  <<: *default
  database: ma_production
  username: ma
  password: <%= ENV['CHAT_PRACTICAL_DATABASE_PASSWORD'] %>
